const fonts = {
  Giorgio_Sans_Bold_Italic: 'Giorgio-Sans-Bold-Italic',
  Giorgio_Sans_Bold: 'Giorgio-Sans-Bold',
  Giorgio_Sans_Extra_Light_Italic: 'Giorgio-Sans-Extra-Light-Italic',
  Giorgio_Sans_Extra_Light: 'Giorgio-Sans-Extra-Light',
  Giorgio_Sans_Light_Italic: 'Giorgio-Sans-Light-Italic',
  Giorgio_Sans_Light: 'Giorgio-Sans-Light',
  Giorgio_Sans_Medium_Italic: 'Giorgio-Sans-Medium-Italic',
  Giorgio_Sans_Medium: 'Giorgio-Sans-Medium',
  Giorgio_Sans_Regular_Italic: 'Giorgio-Sans-Regular-Italic',
  Giorgio_Sans_Regular: 'Giorgio-Sans-Regular',
  Giorgio_Sans_Thin_Italic: 'Giorgio-Sans-Thin-Italic',
  Giorgio_Sans_Thin: 'Giorgio-Sans-Thin',
  Rubik_Black: 'Rubik-Black',
  Rubik_BlackItalic: 'Rubik-BlackItalic',
  Rubik_Bold: 'Rubik-Bold',
  Rubik_BoldItalic: 'Rubik-BoldItalic',
  Rubik_ExtraBold: 'Rubik-ExtraBold',
  Rubik_ExtraBoldItalic: 'Rubik-ExtraBoldItalic',
  Rubik_Italic_VariableFont_wght: 'Rubik-Italic-VariableFont_wght',
  Rubik_Italic: 'Rubik-Italic',
  Rubik_Light: 'Rubik-Light',
  Rubik_LightItalic: 'Rubik-LightItalic',
  Rubik_Medium: 'Rubik-Medium',
  Rubik_MediumItalic: 'Rubik-MediumItalic',
  Rubik_Regular: 'Rubik-Regular',
  Rubik_SemiBold: 'Rubik-SemiBold',
  Rubik_SemiBoldItalic: 'Rubik-SemiBoldItalic',
  Rubik_VariableFont_wght: 'Rubik-VariableFont_wght',
};

export default fonts;
